### ISSUE TITLE
What latest version of mongo can I install? 

### ISSUE THREAD

**Issue by efirity** [rolehippie/mongodb#27]
Hi, can I install mongo 7.0 or 8.0 with this role?

Thanks.

**Comment by efirity** [comment]
seems does not work with version 7 or 6

**Comment by tboerger** [comment]
Generally it could work with current versions, I haven't tried it so far.

Maybe it needs some adjustment to the config related to dropped or added options.

**Comment by tboerger** [comment]
I have merged https://github.com/rolehippie/mongodb/pull/33, bow you would be able to install mongodb up to v8.
